---
title: "Forecast BTC price"
author: "Ignacio"
date: "10/03/2021"
output: html_document
---

```{r setup, include=FALSE}
## install packages

#install.packages("MASS")
#install.packages('forecast', dependencies = TRUE)
#install.packages("tidyverse")
#update.packages("MASS")
#install.packages("RColorBrewer")
#install.packages("gridExtra")
#install.packages("cowplot")
#install.packages("tidyverse")
#install.packages("GGally")
#library(Matrix)
library(gridExtra)
library(cowplot)
#library(viridis)
library(RColorBrewer)
library(tidyverse)
#library(forecast)
library(MASS)

```



```{r}
## 
d <- read.csv("Xday_merged.csv")
daux <- as.Date(d$Date)
d$Date <- daux
head(d)
```

```{r}
## plots

fig00 <- ggplot(data=d)+
  geom_point(aes(x=Date, y=BTC_Close))

fig00
```

```{r}
## Load Data
btc <- read.csv("BTC.csv")
btc$Date <- as.Date(btc$Date)
head(btc)
```


```{r}
dim(d)
dim(btc)

```

```{r}
## plot S2F
df_aux1 <- c(btc$Close, btc$SP500)
df_aux2 <- c()
for (i in 1:2*dim(df_aux1)[1]){
  if (i >= dim(df_aux1)[1]){df_aux2[i] <- "BTC"}
  if (i >dim(df_aux1[1])){df_aux2[i] <- "SP500"}
  
}

df <- data.frame(df_aux1)
df$delim <- 
ggplot(data=btc)+
  geom_point(aes(x=SP500, y=Close, color=))

sum(is.na(btc))
```




```{r}
## plot PI-cycle
fig02 <- ggplot(data=btc)+
  geom_ribbon(aes(x=Date, ymin=Short_Pi, ymax=Long_Pi), fill="grey85", labels="Pi-cycle")+
  geom_line(aes(x=Date, y=Close), color="steelblue")+
  geom_line(aes(x=Date, y=Long_Pi), color="#00AFBB")+
  geom_line(aes(x=Date, y=Short_Pi), color="#FC4E07")+
  scale_y_continuous(trans="log10")+
  labs(y="USD")

fig02

```

```{r}
## Build models
## log variables
lnClose <- log10(btc$Close)
lnS2F <- log10(btc$S2F)

df <- data.frame(lnClose, lnS2F, btc$SP500)

m01 <- lm(data=df, formula=lnClose~I(lnS2F^1))
m02 <- lm(data=df, formula=lnClose~I(lnS2F^2))
m03 <- lm(data=df, formula=lnClose~I(lnS2F^3))
m04 <- lm(data=df, formula=lnClose~I(lnS2F^4))

summary(m01)
summary(m02)
summary(m03)
summary(m04)

```

```{r}
anova(m01, m02, m03, m04)
```

```{r}
## S2F
png("BTC~beta-S2F.png")
fig03 <- ggplot(data=btc)+
  geom_line(aes(x=Date, y=Close), color="steelblue")+
  geom_line(aes(x=Date, y=0.48*S2F^3), color="purple")+
  scale_y_continuous(trans="log10")+
  labs(y="USD")

fig03

dev.off()
```

```{r}
fig04 <- ggplot(data=btc)+
  geom_line(aes(x=Date, y=Close), color="steelblue")+
  #geom_line(aes(x=Date, y=SP500), color="purple")+
  labs(y="USD")+
  #scale_y_continuous(trans="log10")+
  #geom_line(data=d, aes(x=Date, y=tesla_close), color="red")+
  #geom_line(data=d, aes(x=Date, y=gold_close), color="black")+
  geom_line(data=d, aes(x=Date, y=lite_close), color="grey")

fig05 <- ggplot(data=btc)+
  geom_point(aes(x=Date, y=Close), color="steelblue")+
  scale_y_continuous(trans="log10")

fig04
```

$BTC=\beta_0\text{LTC}+\beta_1\text{TSLA}+\ldots$